services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: apache-php
    volumes:
      - .:/var/www
      - ./.docker/php/php.ini:/etc/php/8.1/apache2/php.ini
    ports:
      - 80:80

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: inno-db
    container_name: apache-mysql
    ports:
      - 3306:3306